[global]
disable = [
  "MD013", # Allow long line lengths
  "MD025", # Allow multiple h1 headings
  "MD026", # Permit punctuation in heading
  "MD033", # Permit inline HTML
  "MD041", # Allow first line to be anything (not just h1)
]
extend-enable = ["MD060"] # Table alignment
respect-gitignore = true

[MD060] # Table alignment
enabled = true
style = "aligned"
